# Generated by Django 4.1.3 on 2022-11-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hora', models.DateTimeField()),
                ('disponible', models.BooleanField()),
                ('imagen', models.ImageField(upload_to='barbershopApp/media')),
                ('descripcion', models.TextField(max_length=255)),
            ],
        ),
    ]
