# Generated by Django 4.1.3 on 2022-11-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershopApp', '0004_servicioss_delete_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioss',
            name='imagen',
            field=models.ImageField(upload_to='barberShopApp/fotos'),
        ),
    ]
