# Generated by Django 4.1.3 on 2022-11-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershopApp', '0007_alter_servicioss_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Cortes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hora', models.DateTimeField()),
                ('disponible', models.BooleanField()),
                ('imagen', models.ImageField(upload_to='barbershopApp/static/media')),
                ('descripcion', models.TextField(max_length=255)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Estética',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hora', models.DateTimeField()),
                ('disponible', models.BooleanField()),
                ('imagen', models.ImageField(upload_to='barbershopApp/static/media')),
                ('descripcion', models.TextField(max_length=255)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Peinado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hora', models.DateTimeField()),
                ('disponible', models.BooleanField()),
                ('imagen', models.ImageField(upload_to='barbershopApp/static/media')),
                ('descripcion', models.TextField(max_length=255)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tinte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hora', models.DateTimeField()),
                ('disponible', models.BooleanField()),
                ('imagen', models.ImageField(upload_to='barbershopApp/static/media')),
                ('descripcion', models.TextField(max_length=255)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Servicioss',
            new_name='Barba',
        ),
    ]
