# Generated by Django 4.1.3 on 2022-11-18 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbershopApp', '0008_cliente_cortes_estética_peinado_tinte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='barba_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barbershopApp.barba'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='corte_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barbershopApp.cortes'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estetica_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barbershopApp.estética'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='peindo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barbershopApp.peinado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tinte_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barbershopApp.tinte'),
        ),
    ]
