# Generated by Django 4.1.3 on 2022-11-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershopApp', '0009_cliente_barba_id_cliente_corte_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='barba_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='corte_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estetica_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='peindo_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tinte_id',
        ),
    ]
