# Generated by Django 4.1.3 on 2022-11-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershopApp', '0013_seguimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seguimiento',
        ),
    ]
