# Generated by Django 4.1.3 on 2022-11-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershopApp', '0014_delete_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='barba',
            name='estado',
            field=models.IntegerField(choices=[[0, 'servicio realizado'], [1, 'servicio pendiente']], null=True),
        ),
        migrations.AddField(
            model_name='barba',
            name='pago',
            field=models.IntegerField(choices=[[0, 'reservado'], [1, 'pagado'], [2, 'pendiente de pago'], [3, 'disponible']], null=True),
        ),
        migrations.AddField(
            model_name='cortes',
            name='estado',
            field=models.IntegerField(choices=[[0, 'servicio realizado'], [1, 'servicio pendiente']], null=True),
        ),
        migrations.AddField(
            model_name='cortes',
            name='pago',
            field=models.IntegerField(choices=[[0, 'reservado'], [1, 'pagado'], [2, 'pendiente de pago'], [3, 'disponible']], null=True),
        ),
        migrations.AddField(
            model_name='estética',
            name='estado',
            field=models.IntegerField(choices=[[0, 'servicio realizado'], [1, 'servicio pendiente']], null=True),
        ),
        migrations.AddField(
            model_name='estética',
            name='pago',
            field=models.IntegerField(choices=[[0, 'reservado'], [1, 'pagado'], [2, 'pendiente de pago'], [3, 'disponible']], null=True),
        ),
        migrations.AddField(
            model_name='peinado',
            name='estado',
            field=models.IntegerField(choices=[[0, 'servicio realizado'], [1, 'servicio pendiente']], null=True),
        ),
        migrations.AddField(
            model_name='peinado',
            name='pago',
            field=models.IntegerField(choices=[[0, 'reservado'], [1, 'pagado'], [2, 'pendiente de pago'], [3, 'disponible']], null=True),
        ),
        migrations.AddField(
            model_name='tinte',
            name='estado',
            field=models.IntegerField(choices=[[0, 'servicio realizado'], [1, 'servicio pendiente']], null=True),
        ),
        migrations.AddField(
            model_name='tinte',
            name='pago',
            field=models.IntegerField(choices=[[0, 'reservado'], [1, 'pagado'], [2, 'pendiente de pago'], [3, 'disponible']], null=True),
        ),
    ]
