# Generated by Django 4.1.3 on 2022-12-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershopApp', '0016_alter_barba_imagen_alter_cortes_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barba',
            name='hora',
            field=models.DateTimeField(help_text='Año-Mes-Dia Hora:Minuto'),
        ),
        migrations.AlterField(
            model_name='cortes',
            name='hora',
            field=models.DateTimeField(help_text='Año-Mes-Dia Hora:Minuto'),
        ),
        migrations.AlterField(
            model_name='estética',
            name='hora',
            field=models.DateTimeField(help_text='Año-Mes-Dia Hora:Minuto'),
        ),
        migrations.AlterField(
            model_name='peinado',
            name='hora',
            field=models.DateTimeField(help_text='Año-Mes-Dia Hora:Minuto'),
        ),
        migrations.AlterField(
            model_name='tinte',
            name='hora',
            field=models.DateTimeField(help_text='Año-Mes-Dia Hora:Minuto'),
        ),
    ]
