# Generated by Django 4.1.3 on 2022-12-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershopApp', '0018_alter_peinado_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peinado',
            name='hora',
            field=models.DateTimeField(help_text='Año-Mes-Dia Hora:Minuto'),
        ),
    ]
