# Generated by Django 4.1.3 on 2022-12-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershopApp', '0019_alter_peinado_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
    ]
