# Generated by Django 4.1.3 on 2022-12-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershopApp', '0020_remove_contacto_avisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(help_text='Año-Mes-Dia'),
        ),
    ]
